### PR TITLE
Fixing the entire project structure and libraries

### PR DESCRIPTION
**Pull request by harrychenca**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 75a391ff946b041daa9e18a889ba2a4b894cae94
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/harrychenca/everythingDB

---
This message was auto-generated by https://gitcop.com

**Comment by harrychenca** [comment]
Next time, my commit message would follow the format guarded by GitCop

Something like
`Fix(App Structure): Fixing the entire project structure and libraries`

**Comment by paulld** [comment]
Haha good one, GitCop!
Are removing polymer? bower_components should probably have been added to gitignore initially

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f309f80135df944fd1625f46eec9fc3f3286f27a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/harrychenca/everythingDB

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ed279bf40ddf0363161da71d736891a6a668869f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/harrychenca/everythingDB

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9f512a8c356e090b0b41e3517bec6c78ec6f657
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/harrychenca/everythingDB

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
